# Generated by Django 2.1.2 on 2018-10-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20181022_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='describe',
            field=models.CharField(default='', max_length=100, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.CharField(default='', max_length=100, verbose_name='描述'),
        ),
    ]
