# Generated by Django 2.1.2 on 2018-10-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20181024_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=False, verbose_name='状态：'),
        ),
    ]
