# Generated by Django 2.1.2 on 2018-10-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20181022_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='describe',
            new_name='module_describe',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='module_name',
        ),
    ]
