# Generated by Django 2.1.2 on 2018-10-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_auto_20181023_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_describe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(max_length=20),
        ),
    ]
