# Generated by Django 2.1.1 on 2018-10-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('project_status', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('project_remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
