# Generated by Django 2.1.1 on 2018-10-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
